package club.form;
import club.*;
import java.util.ArrayList;
import static club.Utilities.*;
import java.time.*;

public class ClubManager extends javax.swing.JFrame {

    public static ArrayList<Student> studentList = new ArrayList<>();
    public static ArrayList<Student> memberList = new ArrayList<>();
    public static ArrayList<Bill> billList = new ArrayList<>();
    public static ArrayList<Event> eventList = new ArrayList<>();
    public static ArrayList<Attendance> attendanceList = new ArrayList<>();
    
    
    int numStudents = 0;
    public ClubManager() {
        initComponents();
        studentNum.setText("" + studentList.size());
        memberNum.setText("" + memberList.size());
        billNum.setText("" + billList.size());
        eventNum.setText("" + eventList.size());

        ArrayList<Member> list = new ArrayList<>();
        list.add((Member) memberList.get(0));
        attendanceList.add(new Attendance(list, new Date(10, 31, 2023)));  
        listNum.setText("" + attendanceList.size());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        welcomePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        studentNum = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        memberNum = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        eventNum = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        billNum = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        listNum = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        students = new javax.swing.JLabel();
        members = new javax.swing.JLabel();
        events = new javax.swing.JLabel();
        bills = new javax.swing.JLabel();
        attendance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management");
        setAlwaysOnTop(true);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setForeground(java.awt.Color.white);

        welcomePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Welcome, executive!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("At a glance:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Today's Date: " + LocalDate.now().toString());

        studentNum.setBackground(new java.awt.Color(153, 255, 255));
        studentNum.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        studentNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentNum.setText("" + numStudents);
        studentNum.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(153, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("students");
        jLabel5.setOpaque(true);

        memberNum.setBackground(new java.awt.Color(153, 255, 255));
        memberNum.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        memberNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        memberNum.setText("" + numStudents);
        memberNum.setOpaque(true);

        jLabel11.setBackground(new java.awt.Color(153, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("member(s)");
        jLabel11.setOpaque(true);

        eventNum.setBackground(new java.awt.Color(153, 255, 255));
        eventNum.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        eventNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventNum.setText("" + numStudents);
        eventNum.setOpaque(true);

        jLabel13.setBackground(new java.awt.Color(153, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("event(s)");
        jLabel13.setOpaque(true);

        billNum.setBackground(new java.awt.Color(153, 255, 255));
        billNum.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        billNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billNum.setText("" + numStudents);
        billNum.setOpaque(true);

        jLabel15.setBackground(new java.awt.Color(153, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("bill(s)");
        jLabel15.setOpaque(true);

        listNum.setBackground(new java.awt.Color(153, 255, 255));
        listNum.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        listNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listNum.setText("" + numStudents);
        listNum.setOpaque(true);

        jLabel17.setBackground(new java.awt.Color(153, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("attendance list(s)");
        jLabel17.setOpaque(true);

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(42, 42, 42))
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(welcomePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(welcomePanelLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1))
                    .addGroup(welcomePanelLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentNum, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(memberNum, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eventNum, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(welcomePanelLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(billNum, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(listNum, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(welcomePanelLayout.createSequentialGroup()
                            .addComponent(studentNum, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(welcomePanelLayout.createSequentialGroup()
                            .addComponent(memberNum, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(welcomePanelLayout.createSequentialGroup()
                        .addComponent(eventNum, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(welcomePanelLayout.createSequentialGroup()
                        .addComponent(billNum, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(welcomePanelLayout.createSequentialGroup()
                        .addComponent(listNum, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );

        students.setBackground(new java.awt.Color(202, 240, 248));
        students.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        students.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        students.setText("Student List");
        students.setName(""); // NOI18N
        students.setOpaque(true);
        students.setPreferredSize(new java.awt.Dimension(150, 32));
        students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentsMouseExited(evt);
            }
        });

        members.setBackground(new java.awt.Color(144, 224, 239));
        members.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        members.setForeground(new java.awt.Color(43, 43, 43));
        members.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        members.setText("Members");
        members.setOpaque(true);
        members.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                membersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                membersMouseExited(evt);
            }
        });

        events.setBackground(new java.awt.Color(0, 180, 216));
        events.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        events.setForeground(new java.awt.Color(255, 255, 255));
        events.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        events.setText("Events");
        events.setOpaque(true);
        events.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eventsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eventsMouseExited(evt);
            }
        });

        bills.setBackground(new java.awt.Color(0, 119, 182));
        bills.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bills.setForeground(new java.awt.Color(240, 240, 240));
        bills.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bills.setText("Bills");
        bills.setOpaque(true);
        bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billsMouseExited(evt);
            }
        });

        attendance.setBackground(new java.awt.Color(3, 4, 94));
        attendance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        attendance.setForeground(new java.awt.Color(255, 255, 255));
        attendance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendance.setText("Attendance List");
        attendance.setOpaque(true);
        attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendanceMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(members, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(events, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bills, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attendance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(students, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(welcomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(students, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(members, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(events, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bills, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(attendance, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsMouseEntered
        students.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        
    }//GEN-LAST:event_studentsMouseEntered

    private void studentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsMouseExited
        students.setBorder(null);
    }//GEN-LAST:event_studentsMouseExited

    private void membersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseEntered
        members.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    }//GEN-LAST:event_membersMouseEntered

    private void membersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseExited
        members.setBorder(null);
    }//GEN-LAST:event_membersMouseExited

    private void eventsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsMouseEntered
        events.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    }//GEN-LAST:event_eventsMouseEntered

    private void eventsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsMouseExited
        events.setBorder(null);
    }//GEN-LAST:event_eventsMouseExited

    private void billsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsMouseEntered
        bills.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    }//GEN-LAST:event_billsMouseEntered

    private void billsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsMouseExited
        bills.setBorder(null);
    }//GEN-LAST:event_billsMouseExited

    private void attendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseEntered
        attendance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
    }//GEN-LAST:event_attendanceMouseEntered

    private void attendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseExited
        attendance.setBorder(null);
    }//GEN-LAST:event_attendanceMouseExited

    // Opens the StudentForm when clicked   
    private void studentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsMouseClicked
        StudentForm studentForm = new StudentForm();
        studentForm.setLocationRelativeTo(null);
        studentForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studentsMouseClicked

    // Opens the MemberForm when clicked   
    private void membersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseClicked
        MemberForm memberForm = new MemberForm();
        memberForm.setLocationRelativeTo(null);
        memberForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_membersMouseClicked

    
    // Opens the EventForm when clicked       
    private void eventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsMouseClicked
        EventForm eventForm = new EventForm();
        eventForm.setLocationRelativeTo(null);
        eventForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_eventsMouseClicked

    
    // Opens the BillForm when clicked       
    private void billsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsMouseClicked
        BillForm billForm = new BillForm();
        billForm.setLocationRelativeTo(null);
        billForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_billsMouseClicked

    // Opens the Attendance when clicked       
    private void attendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseClicked
        AttendanceForm attendanceForm = new AttendanceForm();
        attendanceForm.setLocationRelativeTo(null);
        attendanceForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_attendanceMouseClicked
                         
    static {   
        studentList.add(new Student("Evangeline", "Sparks", 9, 243524));
        studentList.add(new Student("Khadijah", "Whitney", 11, 796512));
        studentList.add(new Student("Ann","Hill", 10, 456128));
        studentList.add(new Student("Henri", "Sutton", 9, 712398));
        studentList.add(new Student("Axel", "Duran", 12, 751982));
        studentList.add(new Student("Ashleigh", "Mercado", 9, 810365));
        studentList.add(new Student("Wilbur", "Thornton", 11, 162983));
        studentList.add(new Student("Lana", "Boyd", 12, 984265));
        studentList.add(new Student("Jeremiah", "Castaneda", 10, 195153));
        studentList.add(new Student("Macauley", "Doherty", 9, 813520));
        studentList.add(new Student("Brodie", "Weeks", 12, 102395));
        studentList.add(new Student("Aine", "Nash", 11, 761025));
        studentList.add(new Student("Keira", "Morgan", 12, 995120));
        studentList.add(new Student("Aneesa", "Fischer", 10, 550314));
        studentList.add(new Student("Frazer", "Graves", 9, 808452));
        studentList.add(new Student("Cade", "Leon", 11, 538795));
        studentList.add(new Student("Mason", "Marks", 12, 684105));
        studentList.add(new Student("Alannah", "Hewitt", 9, 675428));
        studentList.add(new Student("Deanna", "Barr", 10, 674815));
        studentList.add(new Student("Nikhil", "Francis", 11, 185492));
        studentList.add(new Student("Hazel", "Morrison",12 ,684193));
        studentList.add(new Student("Liliana", "Hansen", 9 , 648317));
        studentList.add(new Student("Faith", "Roth", 12 , 784910 ));
        studentList.add(new Student("Jason", "Washington", 11 , 893012));
        studentList.add(new Student("Dorothy", "Wallace", 10 , 165035));
        studentList.add(new Student("Findlay", "Bennett", 9 ,  285702));
        studentList.add(new Student("Zaara", "Mcdonald", 9 , 905478));
        studentList.add(new Student("Emilie", "Gates", 11 , 325869));
        studentList.add(new Student("Ayrton", "Whitehead", 12 , 863421));
        studentList.add(new Student("Maisha", "Moore", 10 , 104265));
        
        memberList.add(new Member(studentList.get(search(studentList, "243524", "Student Number")), new Date(1, 12, 2023), 14));
        memberList.add(new Member(studentList.get(search(studentList, "813520", "Student Number")), new Date(12, 12, 2023), 14));
        memberList.add(new Member(studentList.get(search(studentList, "675428", "Student Number")), new Date(5, 10, 2023), 30));
        memberList.add(new Member(studentList.get(search(studentList, "893012", "Student Number")), new Date(5, 12, 2023), 21));
        memberList.add(new Member(studentList.get(search(studentList, "104265", "Student Number")), new Date(5, 12, 2023), 44));
        memberList.add(new Member(studentList.get(search(studentList, "162983", "Student Number")), new Date(5, 7, 2019), 32));
        memberList.add(new Member(studentList.get(search(studentList, "995120", "Student Number")), new Date(5, 6, 2023), 22));
        memberList.add(new Member(studentList.get(search(studentList, "675428", "Student Number")), new Date(5, 2, 2024), 88));
        memberList.add(new Member(studentList.get(search(studentList, "325869", "Student Number")), new Date(1, 22, 2025), 7));
        
        
        billList.add(new Bill(100.00, "Glenforest Admin"));
        eventList.add(new Event("Halloween Event", new Date(10, 31, 2023), new Bill(99.99, "Aditya"))); 

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attendance;
    private javax.swing.JLabel billNum;
    private javax.swing.JLabel bills;
    private javax.swing.JLabel eventNum;
    private javax.swing.JLabel events;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel listNum;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel memberNum;
    private javax.swing.JLabel members;
    private javax.swing.JLabel studentNum;
    private javax.swing.JLabel students;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
