/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package club.form;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import club.*;
import static club.form.ClubManager.*;
import static club.Utilities.*;
import java.time.DateTimeException;
import javax.swing.JOptionPane;
/**
 *
 * @author 920939
 */
public class EventForm extends javax.swing.JFrame {

    ArrayList<String> actions = new ArrayList<>();
    
    public EventForm() {
        initComponents();
        refreshList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        eventPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        dayOfEvent = new javax.swing.JRadioButton();
        billAmount = new javax.swing.JRadioButton();
        searchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sortButton = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        addStudent = new javax.swing.JButton();
        editStudent = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        actionList = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        month = new javax.swing.JTextField();
        day = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        billNumber = new javax.swing.JTextField();
        freeEvent = new javax.swing.JToggleButton();
        billButton = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        members = new javax.swing.JLabel();
        students = new javax.swing.JLabel();
        bills = new javax.swing.JLabel();
        attendance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Events");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setForeground(java.awt.Color.white);

        eventPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Manage Events");

        list.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Search...");

        searchField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        dayOfEvent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dayOfEvent.setText("Day of Event");
        dayOfEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayOfEventActionPerformed(evt);
            }
        });

        billAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        billAmount.setText("Bill Amount");
        billAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billAmountActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchButton.setText("Search!");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Sort by...");

        sortButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sortButton.setText("Sort!");
        sortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortButtonActionPerformed(evt);
            }
        });

        result.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        result.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("Tip: Search and sort by Due Date or Bill Amount!");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Add/Edit Events");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Description:");

        description.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        addStudent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addStudent.setText("Add Event Detail");
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });

        editStudent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editStudent.setText("Edit Event Detail");
        editStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStudentActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clear.setText("Clear...");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        removeButton.setBackground(new java.awt.Color(255, 0, 20));
        removeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("Finish Event");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        actionList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(actionList);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Most Recent Actions:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("(MM/DD/YY)");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Event Date:");

        month.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        day.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        year.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Bill No. ");

        billNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        freeEvent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        freeEvent.setText("Free Event?");
        freeEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeEventActionPerformed(evt);
            }
        });

        billButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        billButton.setText("Show Bills...");
        billButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eventPanelLayout = new javax.swing.GroupLayout(eventPanel);
        eventPanel.setLayout(eventPanelLayout);
        eventPanelLayout.setHorizontalGroup(
            eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventPanelLayout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eventPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eventPanelLayout.createSequentialGroup()
                        .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(eventPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dayOfEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(billAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(eventPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(eventPanelLayout.createSequentialGroup()
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 4, Short.MAX_VALUE))
                            .addComponent(sortButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(eventPanelLayout.createSequentialGroup()
                        .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(result)
                            .addGroup(eventPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(eventPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(eventPanelLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2)
                                            .addGroup(eventPanelLayout.createSequentialGroup()
                                                .addComponent(addStudent)
                                                .addGap(44, 44, 44)
                                                .addComponent(removeButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(editStudent))
                                            .addGroup(eventPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(eventPanelLayout.createSequentialGroup()
                                                .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(99, 99, 99)
                                                .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7))))
                                    .addGroup(eventPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(eventPanelLayout.createSequentialGroup()
                                                .addComponent(billNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(freeEvent)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(billButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        eventPanelLayout.setVerticalGroup(
            eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(eventPanelLayout.createSequentialGroup()
                        .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(searchButton))
                        .addGap(18, 18, 18)
                        .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dayOfEvent)
                            .addComponent(billAmount)
                            .addComponent(jLabel3)
                            .addComponent(sortButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(result)
                        .addGap(24, 24, 24)
                        .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(billNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(freeEvent)
                            .addComponent(billButton))
                        .addGap(15, 15, 15)
                        .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        back.setBackground(new java.awt.Color(202, 240, 248));
        back.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("Back...");
        back.setName(""); // NOI18N
        back.setOpaque(true);
        back.setPreferredSize(new java.awt.Dimension(150, 32));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        members.setBackground(new java.awt.Color(144, 224, 239));
        members.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        members.setForeground(new java.awt.Color(43, 43, 43));
        members.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        members.setText("Members");
        members.setOpaque(true);
        members.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                membersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                membersMouseExited(evt);
            }
        });

        students.setBackground(new java.awt.Color(0, 180, 216));
        students.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        students.setForeground(new java.awt.Color(255, 255, 255));
        students.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        students.setText("Students");
        students.setOpaque(true);
        students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentsMouseExited(evt);
            }
        });

        bills.setBackground(new java.awt.Color(0, 119, 182));
        bills.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bills.setForeground(new java.awt.Color(240, 240, 240));
        bills.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bills.setText("Bills");
        bills.setOpaque(true);
        bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billsMouseExited(evt);
            }
        });

        attendance.setBackground(new java.awt.Color(3, 4, 94));
        attendance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        attendance.setForeground(new java.awt.Color(255, 255, 255));
        attendance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendance.setText("Attendance List");
        attendance.setOpaque(true);
        attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendanceMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(members, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(students, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bills, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attendance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(eventPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eventPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(members, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(students, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bills, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(attendance, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        description.setText(eventList.get(list.getSelectedIndex()).getDescription());
        day.setText("" + eventList.get(list.getSelectedIndex()).getDate().getDay());
        month.setText("" + eventList.get(list.getSelectedIndex()).getDate().getMonth());
        year.setText("" + eventList.get(list.getSelectedIndex()).getDate().getYear());
    }//GEN-LAST:event_listMouseClicked

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void dayOfEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayOfEventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayOfEventActionPerformed

    private void billAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billAmountActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        int index;
        if (dayOfEvent.isSelected()) {
            Date dateToSearch;
            try {
               dateToSearch = new Date(Integer.parseInt(month.getText()), Integer.parseInt(day.getText()), Integer.parseInt(year.getText()));            
            } catch (DateTimeException e) {
                showDialog(this, "Invalid Date!", "Error");
                return;
            }
            index = search(eventList, dateToSearch.toString(), true);
        } else {
            index = search(eventList, billButton.getText(), false);
        }

        if (index >= 0) {
            result.setText("Found " + eventList.get(index).getDescription() + " at position " + (index + 1));
            list.setSelectedIndex(index);
            updateActionList("Search: " + (eventList.get(index).getDescription() + " at position " + (index + 1)));
        } else {
            result.setText("Found 0 results. Perhaps check spelling?");
            updateActionList("Search: 0 results.");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void sortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortButtonActionPerformed
        if (dayOfEvent.isSelected()) {
            sort(eventList, true);
            actions.add(0, "Sort by Date");
        } else if (billAmount.isSelected()) {
            sort(eventList, false);
            actions.add(0, "Sort by Bill");
        } 
        refreshList();
    }//GEN-LAST:event_sortButtonActionPerformed

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        String descriptionString = description.getText().trim();
        int billNum;

        try {
            billNum = Integer.parseInt(billNumber.getText());

            if (billNum <= 0) {
                showDialog(this, "Enter a valid bill number!", "Error");
                return;
            }
        } catch (NumberFormatException e) {
            showDialog(this, "Enter a valid bill number!", "Error");
            return;
        }

        if (descriptionString.equals("")) {
            showDialog(this, "One or more fields is left blank!", "Error");
            return;
        }

        for (int i = 0; i < eventList.size(); i++) {
            Date date;
            try {
               date = new Date(Integer.parseInt(month.getText()), Integer.parseInt(day.getText()), Integer.parseInt(year.getText()));            
            } catch (DateTimeException e) {
                showDialog(this, "Invalid Date!", "Error");
                return;
            }
            int index = search(eventList, date.toString(), true);
            if (index >= 0) {
                showDialog(this, "There already exists the same event at position" + (index + 1), "Error");
                return;
            }
        }
        
        Event event;
        Date date;
        try {
           date = new Date(Integer.parseInt(month.getText()), Integer.parseInt(day.getText()), Integer.parseInt(year.getText()));            
        } catch (DateTimeException e) {
            showDialog(this, "Invalid Date!", "Error");
            return;
        }        
        if (freeEvent.isSelected()) {
            
            event = new Event(descriptionString, date);
        } else {
            event = new Event(descriptionString, date, billList.get(billNum - 1));            
        }
        eventList.add(event);
        refreshList();
        updateActionList("Add Event: " + event);
    }//GEN-LAST:event_addStudentActionPerformed

    private void editStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStudentActionPerformed
        if (list.getSelectedIndex() == -1) {
            showDialog(this, "Select an Event!", "Error");
            return;
        }

        String descriptionValue = description.getText().trim();
        String days = day.getText();
        String months = month.getText();
        String years = year.getText();
        int billNum;

        try {
            billNum = Integer.parseInt(billNumber.getText());

            if (billNum <= 0) {
                showDialog(this, "Enter a valid bill number!", "Error");
                return;
            }
        } catch (NumberFormatException e) {
            showDialog(this, "Enter a valid bill number!", "Error");
            return;
        }

        if (days.equals("") || months.equals("") || years.equals("") || descriptionValue.equals("")) {
            showDialog(this, "One or more fields is left blank!", "Error");
            return;
        }

        Event event = eventList.get(list.getSelectedIndex());
        event.setDescription(descriptionValue);
        Date date;
        try {
           date = new Date(Integer.parseInt(month.getText()), Integer.parseInt(day.getText()), Integer.parseInt(year.getText()));            
        } catch (DateTimeException e) {
            showDialog(this, "Invalid Date!", "Error");
            return;
        }        
        event.setDate(date);
        event.setBill(billList.get(billNum - 1));

        refreshList();
        updateActionList("Edit Event: " + event);
    }//GEN-LAST:event_editStudentActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        description.setText("");
        day.setText("");
        month.setText("");
        year.setText("");
        billNumber.setText("");

        updateActionList("Clear List");
    }//GEN-LAST:event_clearActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        if (eventList.size() == 0) {
            showDialog(this, "There are no events!", "Error");
            return;
        }

        Date date;
        try {
           date = new Date(Integer.parseInt(month.getText()), Integer.parseInt(day.getText()), Integer.parseInt(year.getText()));            
        } catch (DateTimeException e) {
            showDialog(this, "Invalid Date!", "Error");
            return;
        }        

        int index = search(eventList, date.toString(), true);
        if (index < 0) {
            showDialog(this, "Event date not found!", "Error");
            return;
        }

        int n = showConfirmation(this, "Are you sure you want to remove this date?", "Confirmation");

        if (n == 1) {
            // Cancel the removal
            return;
        }

        eventList.remove(index);
        refreshList();

        description.setText("");
        day.setText("");
        month.setText("");
        year.setText("");
        billNumber.setText("");
        list.clearSelection();

        updateActionList("Remove Event");
    }//GEN-LAST:event_removeButtonActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        ClubManager manager = new ClubManager();
        manager.setLocationRelativeTo(null);
        manager.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setBorder(null);
    }//GEN-LAST:event_backMouseExited

    private void membersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseEntered
        members.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    }//GEN-LAST:event_membersMouseEntered

    private void membersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseExited
        members.setBorder(null);
    }//GEN-LAST:event_membersMouseExited

    private void studentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsMouseEntered
        students.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    }//GEN-LAST:event_studentsMouseEntered

    private void studentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsMouseExited
        students.setBorder(null);
    }//GEN-LAST:event_studentsMouseExited

    private void billsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsMouseEntered
        bills.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    }//GEN-LAST:event_billsMouseEntered

    private void billsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsMouseExited
        bills.setBorder(null);
    }//GEN-LAST:event_billsMouseExited

    private void attendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseEntered
        attendance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
    }//GEN-LAST:event_attendanceMouseEntered

    private void attendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseExited
        attendance.setBorder(null);
    }//GEN-LAST:event_attendanceMouseExited

    private void freeEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeEventActionPerformed
        if (freeEvent.isSelected()) {
            billNumber.setText("");
            billNumber.setEnabled(false);
        } else {
            billNumber.setEnabled(true);
        }
    }//GEN-LAST:event_freeEventActionPerformed

    private void billButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billButtonActionPerformed
        String message = "<html>";
        for (int i = 0; i < billList.size(); i++) {
            message += (i + 1) + ". " + billList.get(i).toString() + "<br>";
        }
        JOptionPane.showMessageDialog(this, message, "Bill List", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_billButtonActionPerformed

    private void membersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseClicked
        MemberForm memberForm = new MemberForm();
        memberForm.setLocationRelativeTo(null);
        memberForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_membersMouseClicked

    private void studentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsMouseClicked
        StudentForm studentForm = new StudentForm();
        studentForm.setLocationRelativeTo(null);
        studentForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studentsMouseClicked

    private void billsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsMouseClicked
        BillForm billForm = new BillForm();
        billForm.setLocationRelativeTo(null);
        billForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_billsMouseClicked

    private void attendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseClicked
        AttendanceForm attendanceForm = new AttendanceForm();
        attendanceForm.setLocationRelativeTo(null);
        attendanceForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_attendanceMouseClicked

    public void refreshList() {
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < eventList.size(); i++) {
            model.addElement((i + 1) + ". " + eventList.get(i).toString());
        }
        list.setModel(model);
    }
    
    public void updateActionList(String message) {
        actions.add(0, message);
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < actions.size(); i++) {
            model.addElement(actions.get(i));
        }
        actionList.setModel(model);
    }          

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> actionList;
    private javax.swing.JButton addStudent;
    private javax.swing.JLabel attendance;
    private javax.swing.JLabel back;
    private javax.swing.JRadioButton billAmount;
    private javax.swing.JButton billButton;
    private javax.swing.JTextField billNumber;
    private javax.swing.JLabel bills;
    private javax.swing.JButton clear;
    private javax.swing.JTextField day;
    private javax.swing.JRadioButton dayOfEvent;
    private javax.swing.JTextField description;
    private javax.swing.JButton editStudent;
    private javax.swing.JPanel eventPanel;
    private javax.swing.JToggleButton freeEvent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> list;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel members;
    private javax.swing.JTextField month;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel result;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton sortButton;
    private javax.swing.JLabel students;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
