package club.form;

import javax.swing.DefaultListModel;
import club.*;
import java.util.ArrayList;
import static club.form.ClubManager.*;
import static club.Utilities.*;
import java.time.DateTimeException;
import javax.swing.JOptionPane;

/**
 *
 * @author 920939
 */
public class MemberForm extends javax.swing.JFrame {

    /**
     * Creates new form MemberForm
     */
    ArrayList<String> actions = new ArrayList<>();

    
    public MemberForm() {
        initComponents();
        refreshList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        memberPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sortButton = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        studentNumberField = new javax.swing.JTextField();
        addMember = new javax.swing.JButton();
        editMember = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        actionList = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        experience = new javax.swing.JSlider();
        jLabel12 = new javax.swing.JLabel();
        month = new javax.swing.JTextField();
        day = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        back = new javax.swing.JLabel();
        students = new javax.swing.JLabel();
        events = new javax.swing.JLabel();
        bills = new javax.swing.JLabel();
        attendance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Members");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setForeground(java.awt.Color.white);

        memberPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Manage Members");

        list.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Search...");

        searchField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchButton.setText("Search!");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Sort by...");

        sortButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sortButton.setText("Sort!");
        sortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortButtonActionPerformed(evt);
            }
        });

        result.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        result.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("Tip: Choose the type of value you want to search or sort by!");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Add Member");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Student Number: ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("(MM/DD/YY)");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Exprience Scale:");

        studentNumberField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        addMember.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addMember.setText("Add Member");
        addMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberActionPerformed(evt);
            }
        });

        editMember.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editMember.setText("Edit Member");
        editMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMemberActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clear.setText("Clear...");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        removeButton.setBackground(new java.awt.Color(255, 0, 20));
        removeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("Remove!");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        actionList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(actionList);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Most Recent Actions:");

        type.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Type", "First Name", "Last Name", "Student Number", "Join Date" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Join Date:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setText("Beginner                                       Intermediate                                  Advanced");

        month.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        day.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        year.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout memberPanelLayout = new javax.swing.GroupLayout(memberPanel);
        memberPanel.setLayout(memberPanelLayout);
        memberPanelLayout.setHorizontalGroup(
            memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberPanelLayout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(memberPanelLayout.createSequentialGroup()
                        .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(memberPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(memberPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(memberPanelLayout.createSequentialGroup()
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addComponent(sortButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(memberPanelLayout.createSequentialGroup()
                        .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(result)
                            .addGroup(memberPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(memberPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(memberPanelLayout.createSequentialGroup()
                                        .addComponent(addMember)
                                        .addGap(27, 27, 27)
                                        .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(editMember))
                                    .addComponent(jScrollPane2)
                                    .addGroup(memberPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(memberPanelLayout.createSequentialGroup()
                                        .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(studentNumberField)
                                            .addGroup(memberPanelLayout.createSequentialGroup()
                                                .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(experience, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memberPanelLayout.createSequentialGroup()
                                                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jLabel7)))
                                                    .addComponent(jLabel12))
                                                .addGap(0, 0, Short.MAX_VALUE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        memberPanelLayout.setVerticalGroup(
            memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(memberPanelLayout.createSequentialGroup()
                        .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(searchButton))
                        .addGap(18, 18, 18)
                        .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sortButton)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(result)
                        .addGap(24, 24, 24)
                        .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(studentNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(experience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addMember, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editMember, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        back.setBackground(new java.awt.Color(202, 240, 248));
        back.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("Back...");
        back.setName(""); // NOI18N
        back.setOpaque(true);
        back.setPreferredSize(new java.awt.Dimension(150, 32));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        students.setBackground(new java.awt.Color(144, 224, 239));
        students.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        students.setForeground(new java.awt.Color(43, 43, 43));
        students.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        students.setText("Students");
        students.setOpaque(true);
        students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentsMouseExited(evt);
            }
        });

        events.setBackground(new java.awt.Color(0, 180, 216));
        events.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        events.setForeground(new java.awt.Color(255, 255, 255));
        events.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        events.setText("Events");
        events.setOpaque(true);
        events.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eventsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eventsMouseExited(evt);
            }
        });

        bills.setBackground(new java.awt.Color(0, 119, 182));
        bills.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bills.setForeground(new java.awt.Color(240, 240, 240));
        bills.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bills.setText("Bills");
        bills.setOpaque(true);
        bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billsMouseExited(evt);
            }
        });

        attendance.setBackground(new java.awt.Color(3, 4, 94));
        attendance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        attendance.setForeground(new java.awt.Color(255, 255, 255));
        attendance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendance.setText("Attendance List");
        attendance.setOpaque(true);
        attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendanceMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(students, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(events, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bills, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attendance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(memberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(memberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(students, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(events, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bills, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(attendance, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        Member member = (Member) memberList.get(list.getSelectedIndex());
        
        studentNumberField.setText("" + member.getStudentNumber());
        day.setText("" + member.getJoinDate().getDay());
        month.setText("" + member.getJoinDate().getMonth());
        year.setText("" + member.getJoinDate().getYear());
        
        experience.setValue(member.getExperience());
    }//GEN-LAST:event_listMouseClicked

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        int index;
        
        switch (type.getSelectedItem().toString()) {
            case "First Name":
                index = search(memberList, searchField.getText(), "First Name"); 
                break;
            case "Last Name":
                index = search(memberList, searchField.getText(), "First Name"); 
                break;
            case "Student Number":
                index = search(memberList, searchField.getText(), "Student Number"); 
                break;
            case "Join Date":
                index = search(memberList, searchField.getText(), "Join Date");
                break;      
            default:
                index = search(memberList, searchField.getText(), "First Name");
        }

        if (index >= 0) {
            result.setText("Found " + memberList.get(index).getFirstName() + " " + memberList.get(index).getLastName() + " at position " + (index + 1));
            list.setSelectedIndex(index);
            updateActionList("Search: " + (memberList.get(index).getFirstName() + " " + memberList.get(index).getLastName() + " at position " + (index + 1)));
        } else {
            result.setText("Found 0 results. Perhaps check spelling?");
            updateActionList("Search: 0 results.");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void sortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortButtonActionPerformed
        switch (type.getSelectedItem().toString()) {
            case "First Name":
                sort(memberList, "First Name");
                updateActionList("Sort by First Name");                
                break;
            case "Last Name":
                sort(memberList, "Last Name");
                updateActionList("Sort by Last Name");                
                break;
            case "Student Number":
                sort(memberList, "Student Number");
                updateActionList("Sort by Student Number");                
                break;
            case "Join Date":
                sort(memberList, "Join Date");
                updateActionList("Sort by Join Date");                
                break;      
            default:
                sort(memberList, "First Name");
                updateActionList("Sort by First Name");                
        }
        
        refreshList();
    }//GEN-LAST:event_sortButtonActionPerformed

    private void addMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberActionPerformed
        int studentNumber;

        try {
            studentNumber = Integer.parseInt(studentNumberField.getText());

            if (studentNumberField.getText().length() != 6) {
                showDialog(this, "Enter a valid student number!", "Error");
                return;
            }
        } catch (NumberFormatException e) {
            showDialog(this, "Enter a valid student number!", "Error");
            return;
        }

        int numberIndex = search(studentList, "" + studentNumber, "Student Number");
        
        if (numberIndex < 0) {
            showDialog(this, "There doesn't exist a student with this student number!", "Error");
            return;
        }

        int memberIndex = search(memberList, "" + studentNumber, "Student Number");
        
        if (memberIndex > 0) {
            showDialog(this, "There already is a member!", "Error");
            return;
        }
        
        Date date;
        try {
           date = new Date(Integer.parseInt(month.getText()), Integer.parseInt(day.getText()), Integer.parseInt(year.getText()));            
        } catch (DateTimeException e) {
            showDialog(this, "Invalid Date!", "Error");
            return;
        }

        
        
        Member member = new Member(studentList.get(numberIndex), date, experience.getValue());
        memberList.add(member);
        
        refreshList();
        updateActionList("Add Member: " + member.getInitials());
    }//GEN-LAST:event_addMemberActionPerformed

    private void editMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMemberActionPerformed
        if (list.getSelectedIndex() == -1) {
            showDialog(this, "Select a Member!", "Error");
            return;
        }

        int studentNumber;

        try {
            studentNumber = Integer.parseInt(studentNumberField.getText());

            if (studentNumberField.getText().length() != 6) {
                showDialog(this, "Enter a valid student number!", "Error");
                return;
            }
        } catch (NumberFormatException e) {
            showDialog(this, "Enter a valid student number!", "Error");
            return;
        }

        if (year.getText().trim().equals("") || month.getText().trim().equals("") || day.getText().trim().equals("")) {
            showDialog(this, "One or more fields is left blank!", "Error");
            return;
        }

        if (studentNumber != memberList.get(list.getSelectedIndex()).getStudentNumber()) {
            showDialog(this, "You can't change the student number!", "Error");
            return;
        }

        Member member = (Member) memberList.get(list.getSelectedIndex());
        member.getJoinDate().setMonth(Integer.parseInt(month.getText())); 
        member.getJoinDate().setYear(Integer.parseInt(year.getText()));
        member.getJoinDate().setDay(Integer.parseInt(day.getText()));
        member.setExperience(experience.getValue());

        refreshList();
        updateActionList("Edit Member: " + member.getInitials());
    }//GEN-LAST:event_editMemberActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        studentNumberField.setText("");
        day.setText("");
        year.setText("");
        month.setText("");
        experience.setValue(50);
        list.clearSelection();

        updateActionList("Clear Selection");       
    }//GEN-LAST:event_clearActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        if (memberList.size() == 0) {
            showDialog(this, "There are no members!", "Error");
            return;
        }

        int studentNumber;

        try {
            studentNumber = Integer.parseInt(studentNumberField.getText());

            if (studentNumberField.getText().length() != 6) {
                showDialog(this, "Enter a valid student number!", "Error");
                return;
            }
        } catch (NumberFormatException e) {
            showDialog(this, "Enter a valid student number!", "Error");
            return;
        }

        int index = search(memberList, "" + studentNumber, "Student Number");
        if (index < 0) {
            showDialog(this, "Member not found!", "Error");
            return;
        }

        int n = showConfirmation(this, "Are you sure you want to remove this member?", "Confirmation");

        if (n == 1) {
            // Cancel the removal
            return;
        }

        memberList.remove(index);
        studentNumberField.setText("");
        day.setText("");
        year.setText("");
        month.setText("");
        experience.setValue(50);
        list.clearSelection();
        
        refreshList();
        updateActionList("Remove Member #" + studentNumber);
    }//GEN-LAST:event_removeButtonActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        ClubManager manager = new ClubManager();
        manager.setLocationRelativeTo(null);
        manager.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setBorder(null);
    }//GEN-LAST:event_backMouseExited

    private void studentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsMouseEntered
        students.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    }//GEN-LAST:event_studentsMouseEntered

    private void studentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsMouseExited
        students.setBorder(null);
    }//GEN-LAST:event_studentsMouseExited

    private void eventsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsMouseEntered
        events.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    }//GEN-LAST:event_eventsMouseEntered

    private void eventsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsMouseExited
        events.setBorder(null);
    }//GEN-LAST:event_eventsMouseExited

    private void billsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsMouseEntered
        bills.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    }//GEN-LAST:event_billsMouseEntered

    private void billsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsMouseExited
        bills.setBorder(null);
    }//GEN-LAST:event_billsMouseExited

    private void attendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseEntered
        attendance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
    }//GEN-LAST:event_attendanceMouseEntered

    private void attendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseExited
        attendance.setBorder(null);
    }//GEN-LAST:event_attendanceMouseExited

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void studentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsMouseClicked
        StudentForm studentForm = new StudentForm();
        studentForm.setLocationRelativeTo(null);
        studentForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studentsMouseClicked

    private void eventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsMouseClicked
        EventForm eventForm = new EventForm();
        eventForm.setLocationRelativeTo(null);
        eventForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_eventsMouseClicked

    private void billsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsMouseClicked
        BillForm billForm = new BillForm();
        billForm.setLocationRelativeTo(null);
        billForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_billsMouseClicked

    private void attendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseClicked
        AttendanceForm attendanceForm = new AttendanceForm();
        attendanceForm.setLocationRelativeTo(null);
        attendanceForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_attendanceMouseClicked


    public void refreshList() {
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < memberList.size(); i++) {
            model.addElement((i + 1) + ". " + memberList.get(i).toString());
        }    
        list.setModel(model);        
    }
    
    public void updateActionList(String message) {
        actions.add(0, message);
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < actions.size(); i++) {
            model.addElement(actions.get(i));
        }
        actionList.setModel(model);
    }      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> actionList;
    private javax.swing.JButton addMember;
    private javax.swing.JLabel attendance;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bills;
    private javax.swing.JButton clear;
    private javax.swing.JTextField day;
    private javax.swing.JButton editMember;
    private javax.swing.JLabel events;
    private javax.swing.JSlider experience;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> list;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel memberPanel;
    private javax.swing.JTextField month;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel result;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton sortButton;
    private javax.swing.JTextField studentNumberField;
    private javax.swing.JLabel students;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
