/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package club.form;

import javax.swing.DefaultListModel;
import club.*;
import java.util.*;
import static club.form.ClubManager.*;
import static club.Utilities.*;
import javax.swing.JOptionPane;

/**
 *
 * @author 920939
 */
public class StudentForm extends javax.swing.JFrame {

    ArrayList<String> actions = new ArrayList<>();
    
    /**
     * Creates new form StudentForm
     */
    public StudentForm() {
        initComponents();
        refreshList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        studentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        firstName = new javax.swing.JRadioButton();
        lastName = new javax.swing.JRadioButton();
        studentNumber = new javax.swing.JRadioButton();
        searchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sortButton = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        grade = new javax.swing.JComboBox<>();
        studentNumberField = new javax.swing.JTextField();
        addStudent = new javax.swing.JButton();
        editStudent = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        actionList = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        members = new javax.swing.JLabel();
        events = new javax.swing.JLabel();
        bills = new javax.swing.JLabel();
        attendance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Students");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setForeground(java.awt.Color.white);

        studentPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Manage Students");

        list.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Search...");

        searchField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        buttonGroup1.add(firstName);
        firstName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        firstName.setText("First Name");
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });

        buttonGroup1.add(lastName);
        lastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lastName.setText("Last Name");
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });

        buttonGroup1.add(studentNumber);
        studentNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        studentNumber.setText("Student Number");
        studentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNumberActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchButton.setText("Search!");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Sort by...");

        sortButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sortButton.setText("Sort!");
        sortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortButtonActionPerformed(evt);
            }
        });

        result.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        result.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("Tip: You can search or sort by first name, last name, or student number, case insensitive!");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Add/Edit Student");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("First Name:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Last Name:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Student Number:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Grade:");

        firstNameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lastNameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });

        grade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        grade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Grade", "9", "10", "11", "12" }));

        studentNumberField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        addStudent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addStudent.setText("Add Student Profile");
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });

        editStudent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editStudent.setText("Edit Student Profile");
        editStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStudentActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clear.setText("Clear...");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        removeButton.setBackground(new java.awt.Color(255, 0, 20));
        removeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("Remove!");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        actionList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(actionList);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Most Recent Actions:");

        javax.swing.GroupLayout studentPanelLayout = new javax.swing.GroupLayout(studentPanel);
        studentPanel.setLayout(studentPanelLayout);
        studentPanelLayout.setHorizontalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstName)
                                .addGap(18, 18, 18)
                                .addComponent(lastName)
                                .addGap(18, 18, 18)
                                .addComponent(studentNumber))
                            .addGroup(studentPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentPanelLayout.createSequentialGroup()
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addComponent(sortButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(result)
                            .addGroup(studentPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(studentPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(studentPanelLayout.createSequentialGroup()
                                        .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lastNameField)
                                            .addComponent(firstNameField)))
                                    .addGroup(studentPanelLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(studentPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(studentPanelLayout.createSequentialGroup()
                                                .addComponent(addStudent)
                                                .addGap(27, 27, 27)
                                                .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(editStudent))
                                            .addGroup(studentPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(studentNumberField))
                                            .addComponent(jScrollPane2))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        studentPanelLayout.setVerticalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(searchButton))
                        .addGap(18, 18, 18)
                        .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstName)
                            .addComponent(lastName)
                            .addComponent(studentNumber)
                            .addComponent(jLabel3)
                            .addComponent(sortButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(result)
                        .addGap(24, 24, 24)
                        .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(studentNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        back.setBackground(new java.awt.Color(202, 240, 248));
        back.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("Back...");
        back.setName(""); // NOI18N
        back.setOpaque(true);
        back.setPreferredSize(new java.awt.Dimension(150, 32));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        members.setBackground(new java.awt.Color(144, 224, 239));
        members.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        members.setForeground(new java.awt.Color(43, 43, 43));
        members.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        members.setText("Members");
        members.setOpaque(true);
        members.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                membersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                membersMouseExited(evt);
            }
        });

        events.setBackground(new java.awt.Color(0, 180, 216));
        events.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        events.setForeground(new java.awt.Color(255, 255, 255));
        events.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        events.setText("Events");
        events.setOpaque(true);
        events.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eventsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eventsMouseExited(evt);
            }
        });

        bills.setBackground(new java.awt.Color(0, 119, 182));
        bills.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bills.setForeground(new java.awt.Color(240, 240, 240));
        bills.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bills.setText("Bills");
        bills.setOpaque(true);
        bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billsMouseExited(evt);
            }
        });

        attendance.setBackground(new java.awt.Color(3, 4, 94));
        attendance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        attendance.setForeground(new java.awt.Color(255, 255, 255));
        attendance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendance.setText("Attendance List");
        attendance.setOpaque(true);
        attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendanceMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(members, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(events, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bills, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attendance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(studentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(members, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(events, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bills, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(attendance, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setBorder(null);
    }//GEN-LAST:event_backMouseExited

    private void membersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseEntered
        members.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    }//GEN-LAST:event_membersMouseEntered

    private void membersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseExited
        members.setBorder(null);
    }//GEN-LAST:event_membersMouseExited

    private void eventsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsMouseEntered
        events.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    }//GEN-LAST:event_eventsMouseEntered

    private void eventsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsMouseExited
        events.setBorder(null);
    }//GEN-LAST:event_eventsMouseExited

    private void billsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsMouseEntered
        bills.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    }//GEN-LAST:event_billsMouseEntered

    private void billsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsMouseExited
        bills.setBorder(null);
    }//GEN-LAST:event_billsMouseExited

    private void attendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseEntered
        attendance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
    }//GEN-LAST:event_attendanceMouseEntered

    private void attendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseExited
        attendance.setBorder(null);
    }//GEN-LAST:event_attendanceMouseExited

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void studentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNumberActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        ClubManager manager = new ClubManager();
        manager.setLocationRelativeTo(null);
        manager.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        int index;
        if (firstName.isSelected()) {
            index = search(studentList, searchField.getText(), "First Name");
        } else if (lastName.isSelected()) {
            index = search(studentList, searchField.getText(), "Last Name");
        } else if (studentNumber.isSelected()) {
            if (searchField.getText().length() != 6) {
                result.setText("Student number size should be 6");
                return;
            }
            index = search(studentList, searchField.getText(), "Student Number");
        } else {
            index = search(studentList, searchField.getText(), "First Name");
        }
        
        
        if (index >= 0) {
            result.setText("Found " + studentList.get(index).getFirstName() + " " + studentList.get(index).getLastName() + " at position " + (index + 1));
            list.setSelectedIndex(index);
            updateActionList("Search: " + (studentList.get(index).getFirstName() + " " + studentList.get(index).getLastName() + " at position " + (index + 1)));
        } else {
            result.setText("Found 0 results. Perhaps check spelling?"); 
            updateActionList("Search: 0 results.");
        }
          
    }//GEN-LAST:event_searchButtonActionPerformed

    private void sortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortButtonActionPerformed
        if (firstName.isSelected()) {
            sort(studentList, "First Name");
            updateActionList("Sort by First Name");
        } else if (lastName.isSelected()) {
            sort(studentList, "Last Name");
            updateActionList("Sort by Last Name");
        } else if (studentNumber.isSelected()) {
            sort(studentList, "Student Number");
            updateActionList("Sort by Student Number");
        } else {
            sort(studentList, "First Name");
            updateActionList("Sort by First Name");
        }
        refreshList();        
    }//GEN-LAST:event_sortButtonActionPerformed

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        String firstName = firstNameField.getText().trim();
        String lastName = lastNameField.getText().trim();
        String choice = grade.getSelectedItem().toString();
        int studentNumber;
        
        try {
            studentNumber = Integer.parseInt(studentNumberField.getText());
            
            if (studentNumberField.getText().length() != 6) {
                showDialog(this, "Enter a valid student number!", "Error");
                return;                
            }
        } catch (NumberFormatException e) {
            showDialog(this, "Enter a valid student number!", "Error");
            return;
        }
        
        if (firstName.equals("") || lastName.equals("") || choice.equals("Choose Grade")) {
            showDialog(this, "One or more fields is left blank!", "Error");
            return;
        }
        
        for (int i = 0; i < studentList.size(); i++) {
            int index = search(studentList, "" + studentNumber, "Student Number");
            if (index >= 0) {
                showDialog(this, "There exists a student with this student number at position " + (index + 1), "Error");
                return;
            }
        }
            
        Student student = new Student(firstName, lastName, Integer.parseInt(choice), studentNumber);
        studentList.add(student);
        refreshList();
        updateActionList("Add Student: " + student);
    }//GEN-LAST:event_addStudentActionPerformed

    private void editStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStudentActionPerformed
        if (list.getSelectedIndex() == -1) {
            showDialog(this, "Select a Student!", "Error");
            return;
        }
        
        String firstName = firstNameField.getText().trim();
        String lastName = lastNameField.getText().trim();
        String choice = grade.getSelectedItem().toString();
        int studentNumber;
        
        try {
            studentNumber = Integer.parseInt(studentNumberField.getText());
            
            if (studentNumberField.getText().length() != 6) {
                showDialog(this, "Enter a valid student number!", "Error");
                return;                
            }
        } catch (NumberFormatException e) {
            showDialog(this, "Enter a valid student number!", "Error");
            return;
        }
        
        if (firstName.equals("") || lastName.equals("") || choice.equals("Choose Grade")) {
            showDialog(this, "One or more fields is left blank!", "Error");
            return;
        }
        
        if (studentNumber != studentList.get(list.getSelectedIndex()).getStudentNumber()) {
            showDialog(this, "You can't change the student number!", "Error");
            return;        
        }
        
        Student student = studentList.get(list.getSelectedIndex());
        student.setFirstName(firstName);
        student.setLastName(lastName);
        student.setGrade(Integer.parseInt(choice));
        
        refreshList();
        updateActionList("Edit Student: " + student);           
    }//GEN-LAST:event_editStudentActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        firstNameField.setText("");
        lastNameField.setText("");
        grade.setSelectedIndex(0);
        studentNumberField.setText("");
        list.clearSelection();
        
        updateActionList("Clear List");       
    }//GEN-LAST:event_clearActionPerformed

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        String firstName = studentList.get(list.getSelectedIndex()).getFirstName();
        String lastName = studentList.get(list.getSelectedIndex()).getLastName();
        int grade = studentList.get(list.getSelectedIndex()).getGrade();
        int studentNumber = studentList.get(list.getSelectedIndex()).getStudentNumber();

        firstNameField.setText(firstName);
        lastNameField.setText(lastName);
        this.grade.setSelectedItem("" + grade);
        studentNumberField.setText("" + studentNumber);
    }//GEN-LAST:event_listMouseClicked

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        if (studentList.size() == 0) {
            showDialog(this, "There are no students!", "Error");
            return;
        }
        
        int studentNumber;
        
        try {
            studentNumber = Integer.parseInt(studentNumberField.getText());
            if (studentNumberField.getText().length() != 6) {
                showDialog(this, "Enter a valid student number!", "Error");
                return;                
            }
        } catch (NumberFormatException e) {
            showDialog(this, "Enter a valid student number!", "Error");
            return;
        }
        
        int index = search(studentList, "" + studentNumber, "Student Number");
        if (index < 0) {
            showDialog(this, "Student not found!", "Error");
            return;
        }
            
        int n = showConfirmation(this, "Are you sure you want to remove the student?", "Confirmation");
        
        if (n == 1) {
            // Cancel the removal
            return;
        }
        
        studentList.remove(index);
        firstNameField.setText("");
        lastNameField.setText("");
        grade.setSelectedIndex(0);
        studentNumberField.setText("");
        list.clearSelection();
        
        refreshList();
        updateActionList("Remove Student #" + studentNumber);       
    }//GEN-LAST:event_removeButtonActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void membersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseClicked
        MemberForm memberForm = new MemberForm();
        memberForm.setLocationRelativeTo(null);
        memberForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_membersMouseClicked

    private void eventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsMouseClicked
        EventForm eventForm = new EventForm();
        eventForm.setLocationRelativeTo(null);
        eventForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_eventsMouseClicked

    private void billsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsMouseClicked
        BillForm billForm = new BillForm();
        billForm.setLocationRelativeTo(null);
        billForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_billsMouseClicked

    private void attendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseClicked
        AttendanceForm attendanceForm = new AttendanceForm();
        attendanceForm.setLocationRelativeTo(null);
        attendanceForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_attendanceMouseClicked

    
    public void refreshList() {
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < studentList.size(); i++) {
            model.addElement((i + 1) + ". " + studentList.get(i).toString());
        }    
        list.setModel(model);        
    }
    
    public void updateActionList(String message) {
        actions.add(0, message);
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < actions.size(); i++) {
            model.addElement(actions.get(i));
        }
        actionList.setModel(model);
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> actionList;
    private javax.swing.JButton addStudent;
    private javax.swing.JLabel attendance;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bills;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton editStudent;
    private javax.swing.JLabel events;
    private javax.swing.JRadioButton firstName;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JComboBox<String> grade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton lastName;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JList<String> list;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel members;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel result;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton sortButton;
    private javax.swing.JRadioButton studentNumber;
    private javax.swing.JTextField studentNumberField;
    private javax.swing.JPanel studentPanel;
    // End of variables declaration//GEN-END:variables
}
